### ISSUE TITLE
Multi Tenant not working

### ISSUE THREAD

**Issue by MaheshParmarTaasha** [sumanentc/multitenant#2]
I have clone and import the project with your guidelines(Schema's).
I have register two tenant's with necessary changes. 
using postman I have request for  add city. 
But while fetching the tenant city event Tenant is not exist  in database anywhere.
Still Its returning the data

**Comment by sumanentc** [comment]
the DDL needs to be executed manually. I have updated the Readme. Execute the DDL before starting the application.
